# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

# Middleman Gems
gem 'middleman', '= 4.1.10'
gem 'middleman-search', '=0.8.0'
source 'https://rails-assets.org' do
  gem 'rails-assets-tether', '>= 1.1.0'
end
